// <auto-generated />
using System;
using Kaamil.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Kaamil.Api.Data.Migrations;

[DbContext(typeof(KaamilDbContext))]
partial class KaamilDbContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder
            .HasAnnotation("ProductVersion", "8.0.11")
            .HasAnnotation("Relational:MaxIdentifierLength", 63);

        NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

        modelBuilder.Entity("Kaamil.Api.Models.AppUser", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Email")
                    .IsRequired()
                    .HasMaxLength(256)
                    .HasColumnType("character varying(256)");

                b.Property<string>("FullName")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<bool>("IsActive")
                    .HasColumnType("boolean");

                b.Property<string>("PasswordHash")
                    .IsRequired()
                    .HasColumnType("text");

                b.Property<string>("Role")
                    .IsRequired()
                    .HasMaxLength(32)
                    .HasColumnType("character varying(32)");

                b.HasKey("Id");

                b.HasIndex("Email")
                    .IsUnique();

                b.ToTable("Users");
            });

        modelBuilder.Entity("Kaamil.Api.Models.Category", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("Name")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId", "Name")
                    .IsUnique();

                b.ToTable("Categories");
            });

        modelBuilder.Entity("Kaamil.Api.Models.Report", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<string>("ContentType")
                    .IsRequired()
                    .HasMaxLength(128)
                    .HasColumnType("character varying(128)");

                b.Property<DateTime>("CreatedAt")
                    .HasColumnType("timestamp with time zone");

                b.Property<string>("Description")
                    .HasMaxLength(2000)
                    .HasColumnType("character varying(2000)");

                b.Property<string>("FileName")
                    .IsRequired()
                    .HasMaxLength(260)
                    .HasColumnType("character varying(260)");

                b.Property<long>("FileSize")
                    .HasColumnType("bigint");

                b.Property<string>("StoredFileName")
                    .IsRequired()
                    .HasMaxLength(260)
                    .HasColumnType("character varying(260)");

                b.Property<string>("Title")
                    .IsRequired()
                    .HasMaxLength(200)
                    .HasColumnType("character varying(200)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Reports");
            });

        modelBuilder.Entity("Kaamil.Api.Models.Transaction", b =>
            {
                b.Property<Guid>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("uuid");

                b.Property<decimal>("Amount")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<string>("Category")
                    .IsRequired()
                    .HasMaxLength(120)
                    .HasColumnType("character varying(120)");

                b.Property<DateOnly>("Date")
                    .HasColumnType("date");

                b.Property<string>("Description")
                    .IsRequired()
                    .HasMaxLength(500)
                    .HasColumnType("character varying(500)");

                b.Property<string>("Type")
                    .IsRequired()
                    .HasMaxLength(16)
                    .HasColumnType("character varying(16)");

                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.HasKey("Id");

                b.HasIndex("UserId");

                b.ToTable("Transactions");
            });

        modelBuilder.Entity("Kaamil.Api.Models.UserTotals", b =>
            {
                b.Property<Guid>("UserId")
                    .HasColumnType("uuid");

                b.Property<decimal>("SavedExpense")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<decimal>("SavedIncome")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.Property<decimal>("SavedSavings")
                    .HasPrecision(18, 2)
                    .HasColumnType("numeric(18,2)");

                b.HasKey("UserId");

                b.ToTable("UserTotals");
            });

        modelBuilder.Entity("Kaamil.Api.Models.Category", b =>
            {
                b.HasOne("Kaamil.Api.Models.AppUser", "User")
                    .WithMany("Categories")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Kaamil.Api.Models.Report", b =>
            {
                b.HasOne("Kaamil.Api.Models.AppUser", "User")
                    .WithMany("Reports")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Kaamil.Api.Models.Transaction", b =>
            {
                b.HasOne("Kaamil.Api.Models.AppUser", "User")
                    .WithMany("Transactions")
                    .HasForeignKey("UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Kaamil.Api.Models.UserTotals", b =>
            {
                b.HasOne("Kaamil.Api.Models.AppUser", "User")
                    .WithOne("Totals")
                    .HasForeignKey("Kaamil.Api.Models.UserTotals", "UserId")
                    .OnDelete(DeleteBehavior.Cascade)
                    .IsRequired();

                b.Navigation("User");
            });

        modelBuilder.Entity("Kaamil.Api.Models.AppUser", b =>
            {
                b.Navigation("Categories");

                b.Navigation("Reports");

                b.Navigation("Transactions");

                b.Navigation("Totals");
            });
#pragma warning restore 612, 618
    }
}
